### ISSUE TITLE
invalid version at SemVer

### ISSUE THREAD

**Issue by proclaim** [edjafarov/node-webkit-updater#110]
node: v6.4.0
npm: v3.10.6

anyone has the same error?

TypeError: Invalid Version: {Version}
    at new SemVer (/Users/Jim/Project/flux-studio/public/node_modules/node-webkit-updater/node_modules/semver/semver.js:293:11)
    at SemVer.compare (/Users/Jim/Project/flux-studio/public/node_modules/node-webkit-updater/node_modules/semver/semver.js:342:13)
    at compare (/Users/Jim/Project/flux-studio/public/node_modules/node-webkit-updater/node_modules/semver/semver.js:566:31)
    at Function.gt (/Users/Jim/Project/flux-studio/public/node_modules/node-webkit-updater/node_modules/semver/semver.js:595:10)
    at updater.gotManifest (/Users/Jim/Project/flux-studio/public/node_modules/node-webkit-updater/app/updater.js:75:23)
    at Request.self.callback (/Users/Jim/Project/flux-studio/public/node_modules/node-webkit-updater/node_modules/request/request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/Jim/Project/flux-studio/public/node_modules/node-webkit-updater/node_modules/request/request.js:1063:14)
    at emitOne (events.js:101:20)
/Users/Jim/Project/flux-studio/public/node_modules/node-webkit-updater/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);

**Comment by adam-lynch** [comment]
No sorry. I'm guessing this is a problem with your code / manifest.
